### ISSUE TITLE
Ask for help: Could not find a suitable VTK type for <U1

### ISSUE THREAD

**Issue by AkexStar** [andrewrgarcia/voxelmap#23]
when I try this code:

```python
import voxelmap as vm
import numpy as np

A = np.random.randint(0, 2, (3, 3, 3))
model = vm.Model(A)
model.draw()
```

It can't work

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Alex\anaconda3\envs\vxm\lib\site-packages\voxelmap\main.py", line 436, in draw
    voxel = pyvista.Cube(center=centers[i],x_length=x_len, y_length=y_len, z_length=z_len)
  File "C:\Users\Alex\anaconda3\envs\vxm\lib\site-packages\pyvista\utilities\geometric_objects.py", line 635, in Cube
    cube.cell_data.set_array([1, 4, 0, 3, 5, 2], 'FaceIndex')
  File "C:\Users\Alex\anaconda3\envs\vxm\lib\site-packages\vtkmodules\util\data_model.py", line 171, in set_array
    arr = dsa.numpyTovtkDataArray(copy, name)
  File "C:\Users\Alex\anaconda3\envs\vxm\lib\site-packages\vtkmodules\numpy_interface\dataset_adapter.py", line 146, in numpyTovtkDataArray
    vtkarray = numpy_support.numpy_to_vtk(array, array_type=array_type)
  File "C:\Users\Alex\anaconda3\envs\vxm\lib\site-packages\vtkmodules\util\numpy_support.py", line 146, in numpy_to_vtk
    vtk_typecode = get_vtk_array_type(z.dtype)
  File "C:\Users\Alex\anaconda3\envs\vxm\lib\site-packages\vtkmodules\util\numpy_support.py", line 69, in get_vtk_array_type
    raise TypeError(
TypeError: Could not find a suitable VTK type for <U1
```

I have no idea what happened

**Comment by AkexStar** [comment]
It happened on `Python 3.8.20`

**Comment by andrewrgarcia** [comment]
Hi @AkexStar, 

Thank you for using my package! I did some troubleshooting and found the issue was related to compatibility. I've addressed it by updating the PyVista versions using Poetry.

I've just released a new patch update, **Voxelmap 4.4**. You can upgrade to the latest version by running:

```
pip install --upgrade voxelmap
```

This should resolve the issue as long as your OpenGL graphics drivers are functioning correctly. If you encounter any problems, you can use `draw_mpl` in the terminal or switch to `draw` in a Google Colab notebook as a fallback.

Let me know how it works for you!

Best,  
Andrew
